#!/bin/bash
set -e -o pipefail

apt install -y --no-install-recommends \
    apt-transport-https gnupg2 \
    collectd liboping0 jq dnsutils \
	bpfcc-tools iotop \
	coreutils tree

curl -sSfL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
echo 'deb [arch=amd64] https://download.docker.com/linux/ubuntu cosmic stable' \
    >/etc/apt/sources.list.d/docker-ce.list

apt update
apt install -y --no-install-recommends docker-ce

install -C -m644 collectd.conf -t /etc/collectd/
systemctl restart collectd

if [[ -z "$(docker ps -q -f name='^zipkin$')" ]]; then
	docker rm zipkin || true
	docker pull openzipkin/zipkin
	docker run -d --name=zipkin --network=host --restart=unless-stopped \
		openzipkin/zipkin
fi
